---
title: "Sběr dat"
format: 
  html:
    include-in-header: hero-image.html
    sidebar: false
    anchor-sections: false
    css: [index.css]
editor: 
  markdown: 
    wrap: 72
---

<!-- Accordion začátek -->

<div class="accordion" id="accordionExample">

<!-- 1. STUDENTI -->
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        Studenti
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">

Účastí na výzkumu pomůžeš české společnosti k pochopení toho, **jakým způsobem AI používáš při studiu**, ale i mimo to, v čem se dobře orientuješ a jak na ni nahlížíš.  
<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/V01VLD7KBig?si=_HdzBMF6ltqEXU9H" 
title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; 
gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>

<br>
### Co pro tebe účast na výzkumu znamená?

Nejprve od tebe potřebujeme podepsaný **informovaný souhlas**. To je dokument, který ti vysvětlí, jak bude naloženo se získanými informacemi po dobu výzkumu.  
Nemusíš se však ničeho bát. Data budou ve výsledcích **anonymizována**, což znamená, že tě nikdo nepozná.  
Pak už samotné testování – vyplňování dotazníku. Prvním testem projdeš **na podzim, druhým na jaře**.  
Každé testování zabere zhruba **jednu vyučovací hodinu**.  
Některé otázky mají **časový limit** odpovídající jejich náročnosti.

      </div>
    </div>
  </div>

<!-- 2. UČITELÉ -->
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Učitelé vyplňující dotazník
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">

Vaše účast na výzkumu bude mít **přímý vliv na formování vzdělávací politiky** České republiky vzhledem k užívání AI ve školství.  
<br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/_xshdL3ozl8?si=mLvUlhtksHeesfVe" 
title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; 
gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>

<br>
### Co pro vás účast na výzkumu znamená?

Podepíšete **informovaný souhlas**, který vysvětluje, jak bude s vašimi daty naloženo. Data budou **anonymizována**.  
Testování proběhne ve dvou vlnách: **podzim + jaro**.  
Dotazník ověří znalosti i postoje k AI ve výuce.  
Zabere přibližně **jednu vyučovací hodinu**. Časový limit u otázek odpovídá jejich náročnosti.

      </div>
    </div>
  </div>

<!-- 3. KOORDINÁTOŘI -->
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Školní koordinátoři
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">
Před zahájením testování prosím shlédněte instruktážní video.

<br>
**VIDEO**

      </div>
    </div>
  </div>

<!-- 4. ŘEDITELÉ -->
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Ředitelé
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">

#### Kroky:
<ul>
  <li>E-mailová domluva o:
    <ul>
      <li>souhlasu konání výzkumu</li>
      <li>výběru konkrétních tříd</li>
      <li>domluvě konkrétního času šetření</li>
    </ul>
  </li>
  <li>Dohled nad informovanými souhlasy</li>
  <li>Zaslání jmenných seznamů podle tříd</li>
  <li>Shlédnutí instruktážního videa k průběhu dne</li>
</ul>

      </div>
    </div>
  </div>

<!-- 5. RODIČE -->
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFive">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
        Rodiče
      </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">

Vyjádřením souhlasu s účastí na výzkumu vašeho dítěte **přispíváte k porozumění využívání AI studenty** na středních školách v ČR.  
**Jedná se o první šetření svého druhu na našem území.** Pomůžete nám pochopit úroveň znalostí, schopností i postojů studentů k AI.

      </div>
    </div>
  </div>

</div>
